In [72]:
import pandas as pd
import numpy as np
import os
#Read in images using default viewer
from PIL import Image
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [61]:
os.getcwd()

'/Users/zhaoyiming/Desktop/BT4012/bt4012-in-class-competition'

In [62]:
imgs = os.listdir("/Users/zhaoyiming/Desktop/BT4012/bt4012-in-class-competition/train_images/train_images")
num = len(imgs)

In [63]:
num

6427

In [64]:
imgs

['63.jpg',
 '6400.jpg',
 '823.jpg',
 '4217.jpg',
 '3578.jpg',
 '2666.jpg',
 '5109.jpg',
 '2100.jpg',
 '4571.jpg',
 '1409.jpg',
 '6366.jpg',
 '189.jpg',
 '6372.jpg',
 '2114.jpg',
 '4565.jpg',
 '4203.jpg',
 '2672.jpg',
 '6414.jpg',
 '77.jpg',
 '837.jpg',
 '2882.jpg',
 '3544.jpg',
 '5135.jpg',
 '1353.jpg',
 '1435.jpg',
 '5653.jpg',
 '3222.jpg',
 '5647.jpg',
 '2128.jpg',
 '3236.jpg',
 '4559.jpg',
 '1421.jpg',
 '1347.jpg',
 '2896.jpg',
 '3550.jpg',
 '5121.jpg',
 '638.jpg',
 '5874.jpg',
 '5860.jpg',
 '2869.jpg',
 '1390.jpg',
 '604.jpg',
 '2699.jpg',
 '2841.jpg',
 '3587.jpg',
 '5848.jpg',
 '5690.jpg',
 '162.jpg',
 '6399.jpg',
 '176.jpg',
 '5684.jpg',
 '2855.jpg',
 '3593.jpg',
 '88.jpg',
 '610.jpg',
 '1384.jpg',
 '6164.jpg',
 '4773.jpg',
 '2302.jpg',
 '2464.jpg',
 '4015.jpg',
 '1179.jpg',
 '2470.jpg',
 '4001.jpg',
 '4767.jpg',
 '3008.jpg',
 '2316.jpg',
 '5479.jpg',
 '6170.jpg',
 '3020.jpg',
 '4997.jpg',
 '5451.jpg',
 '6158.jpg',
 '1637.jpg',
 '1151.jpg',
 '5337.jpg',
 '2458.jpg',
 '3746.jpg',


In [65]:
x = np.empty((num,1,28,28),dtype="float32")
for i in range(num):
    img = Image.open("/Users/zhaoyiming/Desktop/BT4012/bt4012-in-class-competition/train_images/train_images/"+imgs[i])
    arr = np.asarray(img,dtype="float32")
    x[i,:,:,:] = arr
    #label[i] = int(imgs[i].split('.')[0])

In [66]:
#Normalize the data by dividing the RGB maximum value 255
x /= 255

In [67]:
x

array([[[[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]]],


       [[[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0

In [68]:
#y_train = np.empty((num,),dtype="uint8")
y = pd.read_csv('train.csv')['label']
y = y.to_numpy()

In [69]:
y

array([1, 0, 0, ..., 0, 0, 0])

In [70]:
# Reshaping the array to 4-dims so that it can work with the Keras API
x = x.reshape(x.shape[0], 28, 28, 1)
# x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)
input_shape = (28, 28, 1)
# Making sure that the values are float so that we can get decimal points after division
x = x.astype('float32')
# x_test = x_test.astype('float32')
# Normalizing the RGB codes by dividing it to the max RGB value.
# x /= 255
# x_test /= 255
print('x shape:', x.shape)
print('Number of images in x', x.shape[0])
# print('Number of images in x_test', x_test.shape[0])


x shape: (6427, 28, 28, 1)
Number of images in x 6427


In [93]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=42)

In [94]:
# Importing the required Keras modules containing model and layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
# Creating a Sequential Model and adding the layers
model = Sequential()
model.add(Conv2D(28, kernel_size=(3,3), input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten()) # Flattening the 2D arrays for fully connected layers
model.add(Dense(128, activation=tf.nn.relu))
model.add(Dropout(0.2))
model.add(Dense(2,activation=tf.nn.softmax))

In [95]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])
model.fit(x=x_train, y=y_train, validation_data=(x_test, y_test), epochs=20)

Train on 5462 samples, validate on 965 samples
Epoch 1/20
5462/5462 [==============================] - 2s 412us/sample - loss: 0.3035 - accuracy: 0.9183 - val_loss: 0.2826 - val_accuracy: 0.9254
Epoch 2/20
5462/5462 [==============================] - 2s 378us/sample - loss: 0.2846 - accuracy: 0.9209 - val_loss: 0.2717 - val_accuracy: 0.9254
Epoch 3/20
5462/5462 [==============================] - 2s 335us/sample - loss: 0.2781 - accuracy: 0.9209 - val_loss: 0.2754 - val_accuracy: 0.9254
Epoch 4/20
5462/5462 [==============================] - 2s 343us/sample - loss: 0.2728 - accuracy: 0.9209 - val_loss: 0.2809 - val_accuracy: 0.9254
Epoch 5/20
5462/5462 [==============================] - 2s 344us/sample - loss: 0.2660 - accuracy: 0.9209 - val_loss: 0.2758 - val_accuracy: 0.9254
Epoch 6/20
5462/5462 [==============================] - 2s 347us/sample - loss: 0.2586 - accuracy: 0.9211 - val_loss: 0.2720 - val_accuracy: 0.9254
Epoch 7/20
5462/5462 [==============================] - 2s 358us/

In [96]:
model.evaluate(x_test, y_test)

965/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.5159960588025305, 0.8994819]

In [97]:
imgs_test = os.listdir("/Users/zhaoyiming/Desktop/BT4012/bt4012-in-class-competition/test_images/test_images")
num = len(imgs_test)

In [98]:
num

1070

In [99]:
# Get the X_test
x_test = np.empty((num,1,28,28),dtype="float32")
label = np.empty((num,),dtype="uint8")
for i in range(num):
    img = Image.open("/Users/zhaoyiming/Desktop/BT4012/bt4012-in-class-competition/test_images/test_images/"+imgs_test[i])
    arr = np.asarray(img,dtype="float32")
    x_test[i,:,:,:] = arr
    label[i] = int(imgs[i].split('.')[0])
#Normalize the data by dividing the RGB maximum value 255
x_test /= 255

In [100]:
x_test

array([[[[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.02352941, 0.        , 0.00392157, ..., 0.        ,
          0.        , 0.        ],
         [0.00784314, 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]]],


       [[[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0

In [86]:
y_test = list()
y_test.append(1)
y_test


[1]

In [103]:
import matplotlib.pyplot as plt
y_test = list()
for i in range(num):
    image_index = i
    #plt.imshow(x_test[image_index].reshape(28, 28),cmap='Greys')
    pred = model.predict(x_test[image_index].reshape(1, 28, 28, 1))
    y_test.append(pred.argmax())

In [104]:
y_test

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [112]:
output = pd.DataFrame(y_test, columns=['target'])
# output
output[output['target']==1].shape

(22, 1)

In [109]:
output.to_csv('output.csv', index=True)

In [ ]:
# baseline cnn model for mnist
from numpy import mean
from numpy import std
from matplotlib import pyplot
from sklearn.model_selection import KFold
from keras.datasets import mnist
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Dense
from keras.layers import Flatten
from keras.optimizers import SGD
 
# load train and test dataset
def load_dataset():
    # load dataset
    (trainX, trainY), (testX, testY) = mnist.load_data()
    # reshape dataset to have a single channel
    trainX = trainX.reshape((trainX.shape[0], 28, 28, 1))
    testX = testX.reshape((testX.shape[0], 28, 28, 1))
    # one hot encode target values
    trainY = to_categorical(trainY)
    testY = to_categorical(testY)
    return trainX, trainY, testX, testY
 
# scale pixels
def prep_pixels(train, test):
    # convert from integers to floats
    train_norm = train.astype('float32')
    test_norm = test.astype('float32')
    # normalize to range 0-1
    train_norm = train_norm / 255.0
    test_norm = test_norm / 255.0
    # return normalized images
    return train_norm, test_norm
 
# define cnn model
def define_model():
    model = Sequential()
    model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=(28, 28, 1)))
    model.add(MaxPooling2D((2, 2)))
    model.add(Flatten())
    model.add(Dense(100, activation='relu', kernel_initializer='he_uniform'))
    model.add(Dense(10, activation='softmax'))
    # compile model
    opt = SGD(lr=0.01, momentum=0.9)
    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
    return model
 
# evaluate a model using k-fold cross-validation
def evaluate_model(dataX, dataY, n_folds=5):
    scores, histories = list(), list()
    # prepare cross validation
    kfold = KFold(n_folds, shuffle=True, random_state=1)
    # enumerate splits
    for train_ix, test_ix in kfold.split(dataX):
        # define model
        model = define_model()
        # select rows for train and test
        trainX, trainY, testX, testY = dataX[train_ix], dataY[train_ix], dataX[test_ix], dataY[test_ix]
        # fit model
        history = model.fit(trainX, trainY, epochs=10, batch_size=32, validation_data=(testX, testY), verbose=0)
        # evaluate model
        _, acc = model.evaluate(testX, testY, verbose=0)
        print('> %.3f' % (acc * 100.0))
        # stores scores
        scores.append(acc)
        histories.append(history)
    return scores, histories
 
# plot diagnostic learning curves
def summarize_diagnostics(histories):
    for i in range(len(histories)):
        # plot loss
        pyplot.subplot(2, 1, 1)
        pyplot.title('Cross Entropy Loss')
        pyplot.plot(histories[i].history['loss'], color='blue', label='train')
        pyplot.plot(histories[i].history['val_loss'], color='orange', label='test')
        # plot accuracy
        pyplot.subplot(2, 1, 2)
        pyplot.title('Classification Accuracy')
        pyplot.plot(histories[i].history['accuracy'], color='blue', label='train')
        pyplot.plot(histories[i].history['val_accuracy'], color='orange', label='test')
    pyplot.show()
 
# summarize model performance
def summarize_performance(scores):
    # print summary
    print('Accuracy: mean=%.3f std=%.3f, n=%d' % (mean(scores)*100, std(scores)*100, len(scores)))
    # box and whisker plots of results
    pyplot.boxplot(scores)
    pyplot.show()
 
# run the test harness for evaluating a model
def run_test_harness():
    # load dataset
    trainX, trainY, testX, testY = load_dataset()
    # prepare pixel data
    trainX, testX = prep_pixels(trainX, testX)
    # evaluate model
    scores, histories = evaluate_model(trainX, trainY)
    # learning curves
    summarize_diagnostics(histories)
    # summarize estimated performance
    summarize_performance(scores)
 
# entry point, run the test harness
run_test_harness()